apiVersion: v1
kind: Service
metadata:
  name: mongo-mongodb
  namespace: kube-system
  labels:
    name: mongo-mongodb
spec:
  selector:
    role: mongo-mongodb
  ports:
  - name: dbport
    protocol: TCP
    port: 27017
  clusterIP: None
