apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo-mongodb
  namespace: kube-system
spec:
  serviceName: "mongo-mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo-mongodb
        mongodb: "true"
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - node1
                  - node2
                  - master1
                  - master2
                  - master3
      containers:
        - name: mongo-mongodb
          image: mongo:3
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: "Asia/Shanghai"
          ports:
          - containerPort: 27017
            name: dbport
          volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db
            subPath: mongodb
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
